# config/api_keys.yaml

# 민감 정보, .gitignore 설정 필수
upbit:
  api_key: YOUR_UPBIT_API_KEY
  secret_key: YOUR_UPBIT_SECRET_KEY
hyperclova:
  key: YOUR_HYPERCLOVA_KEY
market_data_api:
  endpoint: https://api.example.com/stock
  key: YOUR_MARKET_API_KEY
